version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: oj
    versions:
    - 3.11.2
