version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "daily"
    time: "02:00"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: "daily"
    time: "02:00"
